{% set name = "eo-learn-mask" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e92dacfb214fdc2676612c981aa10d003ae0276ceabf28bc748a031a9772222d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [(win and vc<14) or py<35 or python_impl == 'pypy']

requirements:
  host:
    - pip
    - python
  run:
    - eo-learn-core
    - opencv
    - python
    - s2cloudless >=1.3.0
    - python-graphviz
    - dataclasses

test:
  imports:
    - eolearn
    - eolearn.mask

about:
  home: https://github.com/sentinel-hub/eo-learn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A collection of masking utilities and EOTasks
  doc_url: https://pypi.org/project/eo-learn-mask/

extra:
  recipe-maintainers:
    - dcunn
    - mwilson8
    - oblute
    - rluria14
    - benhuff
